workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - credentials
      android_signing:
        - Ouma keystore
      vars:
        PACKAGE_NAME: "com.pubitemsreward.rotate"
    scripts:
      - name: Build Android release
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug
           LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - app/build/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_KEY_FILE
        track: production
        in_app_update_priority: 0
      email:
        recipients:
          - younes.dev97@gmail.com
          - younes.jarhbou2@gmail.com
        notify:
          success: true
          failure: true
